export const errMap = {
	DEFAULT: 'Something went wrong, try again later or contact support.',
	ACC099: 'Please create a deposit and fund your vault before you can create an account.',
	// auth
	AUTH001: 'Please ensure that both email and password are entered correctly.',
	AUTH002: 'The credentials you have entered are incorrect, please try again.',
	AUTH004: 'Account is locked, please contact Customer Support.',
	AUTH005: 'Incorrect OTP Code',
	AUTH006: 'Incorrect OTP Code',
	AUTH007: 'Incorrect OTP Code',
	AUTH008: 'An error occurred, please try again.',
	AUTH009: 'An error occurred, please try again.',
	AUTH010:
		'We are unable to send 2FA SMS to the configured number, please contact Customer Support.',
	AUTH011: 'An error occurred, please try again.',
	AUTH012: 'An error occurred, please try again.',
	AUTH013: 'An error occurred, please try again.',
	AUTH014: 'Account is currently locked.',
	AUTH015: 'An error occurred, please try again.',
	AUTH016: 'An error occurred, please try again.',
	// orchestrator
	ORC001: 'An error occurred, please try again.',
	ORC002: 'An error occurred, please try again.',
	ORC003: 'An error occurred, please try again.',
	ORC004: 'An error occurred, please try again.',
	// rbac
	RBAC001: 'An error occurred, please try again.',
	RBAC002: 'Please log out and login again to refresh your session.',
	RBAC003: 'An error occurred, please try again.',
	RBAC004: 'An error occurred, please try again.',
	RBAC005: 'An error occurred, please try again.',
	RBAC006: 'Please log out and login again to refresh your session.',
	RBAC007: 'Permission denied.',
	RBAC008: 'Too many attempts, please allow 5 minutes before trying again.',
	ACC009: 'An error occurred, please try again.',
	// users
	USERS001: 'Something went wrong, try again later or contact support.',
	USERS002: 'Something went wrong, try again later or contact support.',
	USERS003: 'Something went wrong, try again later or contact support.',
	USERS004: 'An error occurred, please try again.',
	USERS005: 'Something went wrong, try again later or contact support.',
	USERS006: 'Invalid email address provided.',
	USERS007: 'Recovery password attempts exceeded. Try again later.',
	USERS008: 'Something went wrong, try again later or contact support.',
	USERS009: 'You have used this reset link before or it has expired.',
	USERS010: 'Your password needs to be stronger.',
	USERS011:
		'The phone number already used by another account. Please use a different number.',
	USERS012: 'The phone number doesnt match, please try again.',
	USERS013: 'Wrong OTP. Try again.',
	USERS014: 'Something went wrong, try again later or contact support.',
	USERS016: 'To enable SMS authentication, you must add a phone',
	USERS017: '2FA is already enabled for this user',
	USERS018: 'Invalid token provided.',
	USERS019: '2FA is not enabled for this user.',
	USERS020: 'No phone number found.',
	USERS021: 'The user does not exist.',
	USERS022: 'Something went wrong, try again later or contact support.',
	USERS023: 'This user is currently being checked out',
	USERS024: 'Cant uncheck a user that is not checked.',
	USERS025: 'Only the latest editor can uncheck a user.',
	USERS026: 'Cannot modify the password for a superior user account.',
	USERS027: 'The user already exists.',
	USERS028: 'Something went wrong, try again later or contact support.',
	USERS029: 'Something went wrong, try again later or contact support.',
	USERS030: 'Something went wrong, try again later or contact support.',
	USERS031: 'Something went wrong, try again later or contact support.',
	USERS032: 'A user registration already exists.',
	USERS033: 'Something went wrong, try again later or contact support.',
	USERS034: 'Invalid newsletter preferences!',
	// Account service
	ACCOUNT001: 'Unable to create an MT4 account.',
	ACCOUNT002: 'Something went wrong, try again later or contact support.',
	ACCOUNT003: 'Something went wrong, try again later or contact support.',
	ACCOUNT004: 'Something went wrong, try again later or contact support.',
	ACCOUNT005: 'Something went wrong, try again later or contact support.',
	ACCOUNT006: 'Something went wrong, try again later or contact support.',
	ACCOUNT007: 'Something went wrong, try again later or contact support.',
	ACCOUNT008: 'Something went wrong, try again later or contact support.',
	ACCOUNT009: 'Something went wrong, try again later or contact support.',
	ACCOUNT010: 'Something went wrong, try again later or contact support.',
	ACCOUNT011: 'Cannot create demo account.',
	ACCOUNT012: 'Something went wrong, try again later or contact support.',
	ACCOUNT013: 'Something went wrong, try again later or contact support.',
	ACCOUNT014: 'Cannot hide accounts with negative equity.',
	ACCOUNT015: 'Could not complete the change visibility action.',
	ACCOUNT016: 'Something went wrong, try again later or contact support.',
	ACCOUNT017: 'Cannot complete change password.',
	ACCOUNT018: 'Something went wrong, try again later or contact support.',
	ACCOUNT019: 'Cannot complete the change of the leverage.',
	ACCOUNT020: 'Something went wrong, try again later or contact support.',
	ACCOUNT021: 'Failing on updating password.',
	ACCOUNT022: 'Cannot complete updating reference name.',
	ACCOUNT023: 'Something went wrong, try again later or contact support.',
	ACCOUNT024: 'Cannot sync account histories.',
	ACCOUNT025: 'Something went wrong, try again later or contact support.',
	ACCOUNT026: 'Cannot find history for given account.',
	ACCOUNT027: 'Something went wrong, try again later or contact support.',
	ACCOUNT028: 'Cannot sync accounts.',
	ACCOUNT029: 'Something went wrong, try again later or contact support.',
	ACCOUNT030: 'Something went wrong, try again later or contact support.',
	ACCOUNT031: 'Something went wrong, try again later or contact support.',
	ACCOUNT032: 'Something went wrong, try again later or contact support.',
	ACCOUNT033: 'Something went wrong, try again later or contact support.',
	ACCOUNT034: 'Something went wrong, try again later or contact support.',
	ACCOUNT035: 'Something went wrong, try again later or contact support.',
	// transfer
	TRANSFER001: 'Something went wrong, try again later or contact support.',
	TRANSFER002: 'Something went wrong, try again later or contact support.',
	TRANSFER003: 'Something went wrong, try again later or contact support.',
	TRANSFER004: 'Something went wrong, try again later or contact support.',
	TRANSFER005: 'Something went wrong, try again later or contact support.',
	TRANSFER006: 'Something went wrong, try again later or contact support.',
	TRANSFER007: 'Something went wrong, try again later or contact support.',
	TRANSFER008: 'Something went wrong, try again later or contact support.',
	TRANSFER009: 'Something went wrong, try again later or contact support.',
	TRANSFER010: 'Something went wrong, try again later or contact support.',
	TRANSFER011: 'Something went wrong, try again later or contact support.',
	TRANSFER012: 'Something went wrong, try again later or contact support.',
	TRANSFER013: 'Could not update MT4 account balance.',
	TRANSFER014: 'Something went wrong, try again later or contact support.',
	TRANSFER015: 'Error when creating transfer.',
	TRANSFER016: 'Error when creating transfer.',
	TRANSFER017: 'Something went wrong, try again later or contact support.',
	TRANSFER018: 'Something went wrong, try again later or contact support.',
	TRANSFER019: 'Something went wrong, try again later or contact support.',
	TRANSFER020: 'Something went wrong, try again later or contact support.',
	// user request
	UR001: 'Something went wrong, try again later or contact support.',
	UR002: 'Something went wrong, try again later or contact support.',
	UR003: 'Email address already exists.',
	UR004: 'Email address already exists.',
	UR005: 'Something went wrong, try again later or contact support.',
	UR006: 'Something went wrong, try again later or contact support.',
	UR007: 'Something went wrong, try again later or contact support.',
	UR008: 'Something went wrong, try again later or contact support.',
	UR009: 'Something went wrong, try again later or contact support.',
	UR010: 'Something went wrong, try again later or contact support.',
	UR011: 'Something went wrong, try again later or contact support.',
	UR012: 'Something went wrong, try again later or contact support.',
	UR013: 'Something went wrong, try again later or contact support.',
	UR014: 'Something went wrong, try again later or contact support.',
	UR015: 'Something went wrong, try again later or contact support.',
	UR016: 'Something went wrong, try again later or contact support.',
	UR017: 'Something went wrong, try again later or contact support.',
	UR018: 'Something went wrong, try again later or contact support.',
	UR019: 'Something went wrong, try again later or contact support.',
	UR020: 'Something went wrong, try again later or contact support.',
	UR021: 'Something went wrong, try again later or contact support.',
	UR022: 'Something went wrong, try again later or contact support.',
	UR023: 'Something went wrong, try again later or contact support.',
	UR024: 'Phone number already exists.',
	UR025: 'Something went wrong, try again later or contact support.',
	UR026: 'Something went wrong, try again later or contact support.',
	UR027: 'Something went wrong, try again later or contact support.',
	UR028: 'Something went wrong, try again later or contact support.',
	UR029: 'User is under 18 and cannot register.',
	// brand manager
	BMAN001: 'Error getting users',
	BMAN002: 'Error adding users',
	BMAN003: 'No brand ID',
	BMAN004: 'User not valid',
	BMAN005: 'User already exists',
	BMAN006: 'No request body sent',
	BMAN007: 'No user id send in body',
	// misc
	MISC001: 'An error occurred, please try again.',
	MISC002: 'An error occurred, please try again.',
	MISC003: 'An error occurred, please try again.',
	MISC004: 'An error occurred, please try again.',
	MISC005: 'An error occurred, please try again.',
	MISC006: 'An error occurred, please try again.',
	MISC007: 'An error occurred, please try again.',
	MISC008: 'An error occurred, please try again.',
	MISC009: 'An error occurred, please try again.',
	MISC010: 'An error occurred, please try again.',
	MISC011: 'An error occurred, please try again.',
	// payment
	PAYMENT001: 'Something went wrong, try again later or contact support.',
	PAYMENT002: 'Something went wrong, try again later or contact support.',
	PAYMENT003: 'Something went wrong, try again later or contact support.',
	PAYMENT004: 'Could not find deposit',
	PAYMENT005: 'Resource forbidden.',
	PAYMENT006: 'Something went wrong, try again later or contact support.',
	PAYMENT007: 'Error when downloading deposits receipt',
	PAYMENT008: 'Something went wrong, try again later or contact support.',
	PAYMENT009: 'The user is not approved yet.',
	PAYMENT010:
		'Your balance has been locked. Please contact support about locked funds.',
	PAYMENT011:
		'Could not process the request. Please clear cache, refresh and try again.',
	PAYMENT012: 'Your deposit amount is less than expected.',
	PAYMENT013: 'Limit of 5 DEPOSIT TYPES per hour reached.',
	PAYMENT014: 'Skrill Deposit needs a valid email address.',
	PAYMENT015: 'Error when getting deposits list.',
	PAYMENT016: 'Something went wrong, try again later or contact support.',
	PAYMENT017: 'Something went wrong, try again later or contact support.',
	PAYMENT018: 'Something went wrong, try again later or contact support.',
	PAYMENT019: 'Something went wrong, try again later or contact support.',
	PAYMENT020: 'Something went wrong, try again later or contact support.',
	PAYMENT021: 'Your balance has been locked, please contact support.',
	PAYMENT022: 'User is temporarily locked. Please contact support.',
	PAYMENT023: 'Something went wrong, try again later or contact support.',
	PAYMENT024: 'Something went wrong, try again later or contact support.',
	PAYMENT025: 'Something went wrong, try again later or contact support.',
	PAYMENT026: 'Something went wrong, try again later or contact support.',
	PAYMENT027: 'Something went wrong, try again later or contact support.',
	PAYMENT028: 'Something went wrong, try again later or contact support.',
	PAYMENT029: 'Something went wrong, try again later or contact support.',
	PAYMENT030: 'Something went wrong, try again later or contact support.',
	PAYMENT031: 'Something went wrong, try again later or contact support.',
};


